# Generated by Django 2.2.16 on 2022-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, help_text='Обязательное поле. 150 символов или меньше.Только буквы, цифры или символы @/./+/-/_.Не может быть <me>.', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
