# Generated by Django 2.2.16 on 2022-11-13 08:08

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20221110_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Адрес для страницы с группой', unique=True, validators=[django.core.validators.RegexValidator('[a-z0-9_\\-]', message='Некорректное значение поля Slug')], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Адрес для страницы с жанром', unique=True, validators=[django.core.validators.RegexValidator('[a-z0-9_\\-]', message='Некорректное значение поля Slug')], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[reviews.validators.validate_score]),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.validators.year_validator]),
        ),
    ]
